Merge Working Branch
defoebrand/Library pull request #2
Opened 2020-10-30 15:42 UTC by defoebrand

This is the first project in the Microverse Javascript course work.

In it, we were required to accomplish the following:
-   Create and store books in a Book object.
-   Displays each book on the page.
-   “NEW BOOK” button that brings up a form allowing users to input the details for the new book: author, title, number of pages, and whether it’s been read.
-   Button on each book’s display to remove the book from the library.
-   Button on each book’s display to change its read status.

Optional
-   Used localStorage to store book data

2020-10-30 19:07 UTC, adaorachi requested changes
### Hi @defoebrand and @uimarshall :wave: 
Good work on this project, guys. :+1: Your project works fine and as it should. Well-done on adding the local storage features as well. 
However, there are some changes you need to implement in order to get your project approved.
Kindly see my comments and highlighted codes below.

---

### STATUS: CHANGES REQUIRED :recycle: 

---

- [ ] The project description section of your README needs some improvement. It should be different from the Project Specification you already have. You should be able to take about what the project is about and the features you implemented in it.

**The following are optional requirements.**
- [**optional**] Since you already used local storage for preserving data, it'll be nice if when a user deletes a book, it is also deleted from the local storage. This will make your local storage feature look complete and robust.
- [**optional**] It will be nice if you implement some validations for when a user creates a book. A user should not be able to create an empty book or submit an empty input. This does not throw any error but it will improve the user experience of your app if implemented.
- [**optional**] It will be nice if you clear the input fields after a book is submitted, so as to allow a user to create another book without having to clear it manually. And this will also improve the user experience.

---
### After implementing the mandatory changes above, you can request for another code review.
**Note: All requirements not marked with OPTIONAL are considered mandatory.**

---

Should you have any question, do reach out to me on Slack with the username @adaorachi

Happy Coding :relaxed: 

MaryAnn Chukwuka.

2020-10-30 19:07 UTC, adaorachi commented on README.md
> +
- [x] Here, this step is not clear enough. I believe that not every IDE may have this feature. Instead, you should put it this way - `Open the index.html in a browser of your choice`. This is to avoid any misconception of information.

2020-10-30 19:07 UTC, adaorachi commented on scripts/main.js
> +}
- [x] In this function, the requirement states that it should be able to take the user's inputs, but it is not. Rather, you implemented that feature in the submitForm event listener you have below this file. See my comment for that piece of code and I strongly advise you to move that feature to this function to meet the requirement.

2020-10-30 19:07 UTC, adaorachi commented on scripts/main.js
> +  }
- [x] Here, you have a lot of things happening in this function. 
You are displaying the book to the DOM,  you have the delete button feature and you also have the read/unread button toggle feature. 
Remember it is always nice to have a function performing just one single responsibility. 
Kindly refactor your code by putting the `delete button` and `read/unread` button features in their own functions and afterward, call them in this function.

2020-10-30 19:07 UTC, adaorachi commented on scripts/main.js
> +};
- [x] There are a couple of things I want to comment on here. 

First, you shouldn't let a feature or functionality lie loose in a file like the submitForm event listener here. Kindly encapsulate it in a function, as this will help keep your codes organized and modular. You should add it to the `addBookToLibrary` as I've mentioned above.

Secondly, the use of `firstElementChild`, `nextElementSibling`, etc is inappropriate in this case. Assuming in a situation where you have a lot of inputs field values to take care of, it will be unprofessional to keep nesting elements to one another. A better way to do this is to use the attributes you've assigned to these elements in your HMTL file to get their values.
Something like this - `const title = document.querySelector('input[name=addTitle]')` or you can assign ID attributes to the elements and get their values like this - `const title = document.getElementById('addTitle')`
And if you want to take it a step further by using the ES6 syntaxes, you can do something similar to this - 
```
  let formValues = [];
  ['addTitle', 'addAuthor', 'addPages', 'haveRead'].forEach(val => formValues.push(document.querySelector(`input[name=${val}]`)))
  let [title, author, pages, checkbox] = formValues;
  addBookToLibrary(title.value, author.value, pages.value, checkIfRead(checkbox.checked));
```

2020-11-02 13:40 UTC, rOluochKe approved these changes
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-02 13:50 UTC, merged